version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5433:5432"