version: "3.9"

services:
  app:
    build: .
    container_name: wallet_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/walletdb
      SPRING_DATASOURCE_USERNAME: wallet_user
      SPRING_DATASOURCE_PASSWORD: wallet_pass
      SPRING_LIQUIBASE_ENABLED: "true"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: